### ISSUE TITLE
UInt casting issue

### ISSUE THREAD

**Issue by jozsef-vesza** [lvsti/NimbleMockSix#2]
When writing an expectation for an API which accepts an `UInt` parameter, the code below will fail (due to conditional casting):

```swift
expect(myClass).toEventually(receive(.api_call, with: [theValue(2)]))
```

This is more problematic when you write an expectation with `toNotEventually`, as it will pass, and this issue will be hidden.

As a workaround, it is possible to pass a UInt:

```swift
expect(myClass).toEventually(receive(.api_call, with: [theValue(UInt(2))]))
```

**Comment by lvsti** [comment]
Nice catch! The problem is that `receive` doesn't have any type information regarding the method arguments and so the verifiers cannot be constrained and have to accept `Any?`. Now, as you pointed out, this value was cast fallibly to the expected value's type which could silently give back an erroneous result. So in this case I'm leaning towards crashing the expectation right away (replacing `as?` with `as!`) because the type mismatch is a programmer error.
